config/routes.rb
Rails.application.routes.draw do

  
  resources :comment_sells
  

  resources :activities

  resources :albumtens do 
    member do
    get "like", to: "albumtens#upvote"
    get "dislike", to: "albumtens#downvote"
  end 
end 

  resources :albumeights do 
  member do
    get "like", to: "albumeights#upvote"
    get "dislike", to: "albumeights#downvote"
  end 
end 

  resources :albumsevens do 

  member do
    get "like", to: "albumsevens#upvote"
    get "dislike", to: "albumsevens#downvote"
  end 
end 
  resources :albumsixs do 

  member do
    get "like", to: "albumsixes#upvote"
    get "dislike", to: "albumsixes#downvote"
  end 
end 
  resources :albumnines do 

  member do
    get "like", to: "albumnines#upvote"
    get "dislike", to: "albumnines#downvote"
  end 
end 
  resources :albumfours do 

  member do
    get "like", to: "albumfours#upvote"
    get "dislike", to: "albumfours#downvote"
  end 
end 
  resources :albumthrees do 

  member do
    get "like", to: "albumthrees#upvote"
    get "dislike", to: "albumthrees#downvote"
  end 
end 
  resources :albumtwos do 

  member do
    get "like", to: "albumtwos#upvote"
    get "dislike", to: "albumtwos#downvote"
  end 
end 
  resources :albumones do 

  member do
    get "like", to: "albumones#upvote"
    get "dislike", to: "albumones#downvote"
  end 
end 

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  resources :forums do 
  member do
    get "like", to: "forums#upvote"
    get "dislike", to: "forums#downvote"
  end 
end 

  resources :whips
  resources :comments
devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :events

  resources :sells do 

  member do
    get "like", to: "sells#upvote"
    get "dislike", to: "sells#downvote"
  end 
end 

  root 'welcome#index'

  get 'events' => 'welcome#events'

  get 'shoutouts' => 'whips#index'

  get 'forum' => 'forums#index'

  get 'partout' => 'welcome#partout'

  get 'videos' => 'welcome#videos'

  get 'contacts' => 'welcome#contact'

  get 'fam1' => 'welcome#fam1'

   get 'fam2' => 'welcome#fam2'

    get 'fam3' => 'welcome#fam3'

     get 'fam4' => 'welcome#fam4'

      get 'fam5' => 'welcome#fam5'

       get 'fam6' => 'welcome#fam6'

        get 'fam7' => 'welcome#fam7'

         get 'fam8' => 'welcome#fam8'

          get 'fam9' => 'welcome#fam9'

           get 'fam10' => 'welcome#fam10'

            get 'fam11' => 'welcome#fam11'

             get 'fam12' => 'welcome#fam12'

              get 'fam13' => 'welcome#fam13'

               get 'fam14' => 'welcome#fam14'

                get 'fam15' => 'welcome#fam15'

                 get 'fam16' => 'welcome#fam16'

                  get 'fam17' => 'welcome#fam17'

                   get 'fam18' => 'welcome#fam18'

                    get 'fam19' => 'welcome#fam19'

                     get 'fam20' => 'welcome#fam20'

                      get 'fam21' => 'welcome#fam21'

                       get 'fam22' => 'welcome#fam22'

                        get 'fam23' => 'welcome#fam23'

                         get 'fam24' => 'welcome#fam24'

                          get 'fam25' => 'welcome#fam25'

                           get 'fam26' => 'welcome#fam26'

                            get 'fam27' => 'welcome#fam27'

                             get 'fam28' => 'welcome#fam28'

  
end

app/models/albumseven.rb
class Albumseven < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
belongs_to :user
acts_as_votable
validates :title, :presence => true
 def score
  self.get_upvotes.size - self.get_downvotes.size
end
end

app/controllers/albumsevens_controller.rb
class AlbumsevensController < ApplicationController
  before_action :set_albumseven, only: [:show, :edit, :update, :destroy]

  # GET /albumsevens
  # GET /albumsevens.json
  def index
    @albumsevens = Albumseven.all.order("created_at DESC")
  end

  # GET /albumsevens/1
  # GET /albumsevens/1.json
  def show
  end

  # GET /albumsevens/new
  def new
    @albumseven = Albumseven.new
  end

  # GET /albumsevens/1/edit
  def edit
  end

  # POST /albumsevens
  # POST /albumsevens.json
  def create
    @albumseven = Albumseven.new(albumseven_params)

    respond_to do |format|
      if @albumseven.save
         User.find_each do |user|
        AlbumsevenMailer.albumseven_notification(@albumseven).deliver
      end
        format.html { redirect_to @albumseven, notice: 'Albumseven was successfully created.' }
        format.json { render :show, status: :created, location: @albumseven }
      else
        format.html { render :new }
        format.json { render json: @albumseven.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albumsevens/1
  # PATCH/PUT /albumsevens/1.json
  def update
    respond_to do |format|
      if @albumseven.update(albumseven_params)
        format.html { redirect_to @albumseven, notice: 'Albumseven was successfully updated.' }
        format.json { render :show, status: :ok, location: @albumseven }
      else
        format.html { render :edit }
        format.json { render json: @albumseven.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albumsevens/1
  # DELETE /albumsevens/1.json
  def destroy
    @albumseven.destroy
    respond_to do |format|
      format.html { redirect_to albumsevens_url, notice: 'Albumseven was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @albumseven = Albumseven.find(params[:id])
    @albumseven.upvote_by current_user
    redirect_to albumsevens_path
  end
  def downvote
  @albumseven = Albumseven.find(params[:id])
  @albumseven.downvote_by current_user
  redirect_to albumsevens_path
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_albumseven
      @albumseven = Albumseven.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def albumseven_params
      params.require(:albumseven).permit(:title, :avatar, :user_id)
    end
end

app/helpers/albumsevens_helper.rb
module AlbumsevensHelper
end

app/views/albumsevens/_form.html.erb
<%= simple_form_for(@albumseven) do |f| %>
  <%= f.error_notification %>

    <div class="container">

  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id%>
  </div>

  <div class="form-group">
  <div class="required">*Title Required*</div>
    <%= f.input_field :title, placeholder:"Title - limit to 40 characters",:maxlength => 40, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Create Post", class:"btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/albumsevens/edit.html.erb
<h1>Editing Albumseven</h1>

<%= render 'form' %>

<%= link_to 'Show', @albumseven %> |
<%= link_to 'Back', albumsevens_path %>

app/views/albumsevens/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="part_out">Cindy, Wayne & Family</h1>


<%= link_to 'Add New Photo', new_albumseven_path, class:"btn btn-primary add" %>

<div class="somespace"></div>


  <div>
    <% @albumsevens.each do |albumseven| %>
      <div class="col-md-6">
        
        <% if albumseven.avatar.file? %>  

        <div class="album_top">
        <p class="sell_description text_board"><a class="avatar_forum"> <%= image_tag(albumseven.user.avatar, class:"avatar_album") %></a>  <strong><%= albumseven.user.user_name %> </strong></p>      
        </div>      
        <a> <%= image_tag albumseven.avatar, class:"img-responsive photoalbums"%></a>
        <div class="phototitle"><%= albumseven.title %><% if current_user.id == albumseven.user.id || current_user.admin%>
        <div class="dropdown2">
  <button class="dropbtn2">Options</button>
  <div class="dropdown-content2">
    <a> <%= link_to 'Edit', edit_albumseven_path(albumseven)%> </a>
    <a>  <%= link_to 'Delete', albumseven, method: :delete, data: { confirm: 'Are you sure?' } %></a>
  </div>
</div>
       <%end%>
       <p class="like_circle2"><%= link_to "", like_albumseven_path(albumseven), class:"glyphicon glyphicon-thumbs-up like2"%><a class="count_score2"><%= albumseven.score %></a></div>
<%end%>
        
      </div>
      <div class="somespace"></div>
    <% end %>
<div class="somemorespace"></div>

app/views/albumsevens/new.html.erb
<h1 class="part_out">Cindy, Wayne & Family</h1>

<%= render 'form' %>

<%= link_to 'Back', albumsevens_path %>

app/views/albumsevens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @albumseven.title %>
</p>

<%= link_to 'Edit', edit_albumseven_path(@albumseven) %> |
<%= link_to 'Back', albumsevens_path %>