config/routes.rb
Rails.application.routes.draw do

  
  resources :comment_sells
  

  resources :activities

  resources :albumtens do 
    member do
    get "like", to: "albumtens#upvote"
    get "dislike", to: "albumtens#downvote"
  end 
end 

  resources :albumeights do 
  member do
    get "like", to: "albumeights#upvote"
    get "dislike", to: "albumeights#downvote"
  end 
end 

  resources :albumsevens do 

  member do
    get "like", to: "albumsevens#upvote"
    get "dislike", to: "albumsevens#downvote"
  end 
end 
  resources :albumsixs do 

  member do
    get "like", to: "albumsixes#upvote"
    get "dislike", to: "albumsixes#downvote"
  end 
end 
  resources :albumnines do 

  member do
    get "like", to: "albumnines#upvote"
    get "dislike", to: "albumnines#downvote"
  end 
end 
  resources :albumfours do 

  member do
    get "like", to: "albumfours#upvote"
    get "dislike", to: "albumfours#downvote"
  end 
end 
  resources :albumthrees do 

  member do
    get "like", to: "albumthrees#upvote"
    get "dislike", to: "albumthrees#downvote"
  end 
end 
  resources :albumtwos do 

  member do
    get "like", to: "albumtwos#upvote"
    get "dislike", to: "albumtwos#downvote"
  end 
end 
  resources :albumones do 

  member do
    get "like", to: "albumones#upvote"
    get "dislike", to: "albumones#downvote"
  end 
end 

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  resources :forums do 
  member do
    get "like", to: "forums#upvote"
    get "dislike", to: "forums#downvote"
  end 
end 

  resources :whips
  resources :comments
devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :events

  resources :sells do 

  member do
    get "like", to: "sells#upvote"
    get "dislike", to: "sells#downvote"
  end 
end 

  root 'welcome#index'

  get 'events' => 'welcome#events'

  get 'shoutouts' => 'whips#index'

  get 'forum' => 'forums#index'

  get 'partout' => 'welcome#partout'

  get 'videos' => 'welcome#videos'

  get 'contacts' => 'welcome#contact'

  get 'fam1' => 'welcome#fam1'

   get 'fam2' => 'welcome#fam2'

    get 'fam3' => 'welcome#fam3'

     get 'fam4' => 'welcome#fam4'

      get 'fam5' => 'welcome#fam5'

       get 'fam6' => 'welcome#fam6'

        get 'fam7' => 'welcome#fam7'

         get 'fam8' => 'welcome#fam8'

          get 'fam9' => 'welcome#fam9'

           get 'fam10' => 'welcome#fam10'

            get 'fam11' => 'welcome#fam11'

             get 'fam12' => 'welcome#fam12'

              get 'fam13' => 'welcome#fam13'

               get 'fam14' => 'welcome#fam14'

                get 'fam15' => 'welcome#fam15'

                 get 'fam16' => 'welcome#fam16'

                  get 'fam17' => 'welcome#fam17'

                   get 'fam18' => 'welcome#fam18'

                    get 'fam19' => 'welcome#fam19'

                     get 'fam20' => 'welcome#fam20'

                      get 'fam21' => 'welcome#fam21'

                       get 'fam22' => 'welcome#fam22'

                        get 'fam23' => 'welcome#fam23'

                         get 'fam24' => 'welcome#fam24'

                          get 'fam25' => 'welcome#fam25'

                           get 'fam26' => 'welcome#fam26'

                            get 'fam27' => 'welcome#fam27'

                             get 'fam28' => 'welcome#fam28'

  
end

app/models/sell.rb
class Sell < ActiveRecord::Base

 
  has_many :comment_sells

  belongs_to :user

has_attached_file :avatar,
  :convert_options => { :all => '-auto-orient' },
  styles: { original: "", thumb: "200x200#" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
acts_as_votable
def score
  self.get_upvotes.size - self.get_downvotes.size
end

end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  before_action :set_sell, only: [:show, :edit, :update, :destroy]

   before_action :authenticate_user!
  # GET /sells
  # GET /sells.json
  def index
    @sells = Sell.all.order("created_at DESC")

  end

  # GET /sells/1
  # GET /sells/1.json
  def show
    @comment = Comment.new
  end

  # GET /sells/new
  def new
    @sell = Sell.new
  end

  # GET /sells/1/edit
  def edit
  end

  # POST /sells
  # POST /sells.json
  def create
    @sell = Sell.new(sell_params)
    respond_to do |format|
      if @sell.save
        User.find_each do |user|
        SellsMailer.sell_notification(@sell).deliver
      end
        format.html { redirect_to @sell, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @sell }
      else
        format.html { render :new }
        format.json { render json: @sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sells/1
  # PATCH/PUT /sells/1.json
  def update
    respond_to do |format|
      if @sell.update(sell_params)
        format.html { redirect_to @sell, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @sell }
      else
        format.html { render :edit }
        format.json { render json: @sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sells/1
  # DELETE /sells/1.json
  def destroy
    @sell.destroy
    respond_to do |format|
      format.html { redirect_to sells_url, notice: 'Listing was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @sell = Sell.find(params[:id])
    @sell.upvote_by current_user
    redirect_to sells_path
  end
  def downvote
  @sell = Sell.find(params[:id])
  @sell.downvote_by current_user
  redirect_to sells_path
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sell
      @sell = Sell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sell_params
      params.require(:sell).permit(:name, :email, :title, :description, :price, :avatar, :sell_id, :user_id)
    end

end

app/helpers/sells_helper.rb
module SellsHelper
end

app/views/sells/_form.html.erb
<%= form_for(@sell) do |f| %>
  <% if @sell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sell.errors.count, "error") %> prohibited this sell from being saved:</h2>

      <ul>
      <% @sell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">

  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id%>
  </div>

  <div class="form-group">
    <%= f.text_field :title, placeholder:"Title", class:"form-control"  %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder:"Description", class:"form-control"  %>
  </div>
  <div class="form-group">
    <%= f.number_field :price, placeholder:"Price - Leave blank if item is free", class:"form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/sells/edit.html.erb
<h1>Edit Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @sell, class:"btn btn-primary add" %> |
<%= link_to 'Back', sells_path, class:"btn btn-primary add" %>

app/views/sells/index.html.erb
<h1 class="part_out">Family Giveaway <%= image_tag "giveaway.png", alt: "Atlanta Atlanta Genesis Coupe picture", class: "camera" %></h1>

<%= link_to 'Add a New Item', new_sell_path, class:"btn btn-primary add"%>


<br>


    <% @sells.each do |sell| %>
     <div class="col-md-4">
        <div class="well index-wells">
    <% if current_user.id == sell.user.id || current_user.admin%>
        <div class="dropdown">
  <button class="dropbtn">Options</button>
  <div class="dropdown-content">
    <a> <%= link_to 'Edit', edit_sell_path(sell)%> </a>
    <a>  <%= link_to 'Delete', sell, method: :delete, data: { confirm: 'Are you sure?' } %></a>
  </div>
</div>
       <%end%>

       <% if sell.price == 0 || sell.price.blank?%>
       <h4 class="title_price text_board"><%= "#{sell.title} || Free!"%></h4>
       <%else%>
        <h4 class="title_price text_board"><%= "#{sell.title} || $#{sell.price}"%></h4>
        <!-- <p><strong>Description</strong> <%= sell.description %></p>--> 

        <%end%>
           <p class="sell_description text_board"><a class="avatar_forum"> <%= image_tag(sell.user.avatar, class:"avatar_forum") %></a>  <strong><%= sell.user.user_name %> </strong></p>
        <% if sell.description.blank?%>

        <%else%>
        <p class="sell_description text_board"><strong>Description:</strong> <%= sell.description %></p>
        <%end%>
<% if sell.avatar.file? %>        
        <a> <%= image_tag sell.avatar, class:"img-responsive img_user"%></a>
<%end%>

        <a> <%= link_to "Comment (#{sell.comment_sells.count})", sell, class:"com_btn btn btn-primary"%><%=  %></a><p class="like_circle"><%= link_to "", like_sell_path(sell), class:"glyphicon glyphicon-thumbs-up like"%><a class="count_score"><%= sell.score %></a> </p>

       <div class="text_board"><%= sell.created_at.localtime.strftime("%m/%d/%Y at %I:%m %p") %> </div>
</div>
</div>
   
  <% end %>

app/views/sells/new.html.erb
<h1 class="part_out">New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', sells_path, class:"btn btn-primary add"%>

app/views/sells/show.html.erb
<div class="container max">
   <br />

  <%= link_to 'Back', sells_path, class:"btn btn-primary add"%>


        <div class="well index-wells">
       
       <% if @sell.price == 0 || @sell.price.blank?%>
       <h4 class="title_price text_board"><%= "#{@sell.title} || Free!"%></h4>
       <%else%>
        <h4 class="title_price text_board"><%= "#{@sell.title} || $#{@sell.price}"%></h4>
        

        <%end%>

        <% if @sell.description.blank?%>

        <%else%>
        <p class="sell_description"><strong>Description:</strong> <%= @sell.description %></p>
        <%end%>
        <% if @sell.avatar.file? %> 
        <a> <%= image_tag @sell.avatar, class:"img-responsive img_user"%></a>
       <%end%>
        </div>









  </div>

  <div class="well index-wells max form_over">
  <% @sell.comment_sells.each do |comment_sell| %>
  <% if current_user.id == comment_sell.user.id || current_user.admin%>
    
             <a>  <%= link_to '', comment_sell, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary delete glyphicon glyphicon-trash" %></a>
       <% end %>
    <div class="sizing">
<p class="hater"> <p class="sell_description text_board"><a class="avatar_forum"> <%= image_tag(comment_sell.user.avatar, class:"avatar_forum")%>  </a><strong><%= comment_sell.user.user_name %>:</strong> <%= comment_sell.comment_entry %></p> 
<% if comment_sell.avatar.file? %>
<a> <%= image_tag comment_sell.avatar, class:"img-responsive img_user"%></a>
<%end%>


      <div class="time"><%= comment_sell.created_at.localtime.strftime("%m/%d/%Y at %I:%m %p") %> </div>

      

    
     
   </div>
  <% end %>
  
  

 </div>
<div class="text_area">
  <%= render 'comment_sells/form' %>
</div>
</div>